config {
  type: "table",
  schema: "gold",
  tags: ["trends", "ads"]
}

SELECT
  fa.start_date AS date,
  fa.search_term,
  gt.interest AS search_interest
FROM
  ${ref("facebook_ads_clean")} AS fa
LEFT JOIN
  ${ref("google_trends_clean")} AS gt
ON
  fa.start_date = gt.date
  AND TRIM(LOWER(fa.search_term)) = TRIM(LOWER(gt.search_term))
WHERE
  fa.search_term IS NOT NULL
  AND fa.start_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 60 DAY)
  AND gt.interest IS NOT NULL
